/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Patcher_Listener */

#ifndef _Included_Patcher_Listener
#define _Included_Patcher_Listener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
